// Generated by scripts/build-problems.mjs from system-design.md. Do not edit.
import type { LayerId } from "@/lib/types";

export type ProblemMeta = {
  id: string;
  n: number;
  title: string;
  layer: LayerId;
  asked: string;
};

export const problems: ProblemMeta[] = [
  {
    "id": "catalog-retrieval-at-scale",
    "n": 1,
    "title": "Catalog retrieval at 500 million rows",
    "layer": "retrieval",
    "asked": "Our enterprise database holds 500 million product metadata rows. Standard top-k vector retrieval is returning irrelevant chunks, which causes hallucination and blows through our token budgets. How do you re-architect this context ingestion pipeline to improve accuracy and control cost?"
  },
  {
    "id": "filter-selectivity-collapse",
    "n": 2,
    "title": "Filter selectivity collapse",
    "layer": "retrieval",
    "asked": "The same catalog search works fine for broad queries but returns near-empty or nonsensical results whenever a user applies three or more filters. Recall drops off a cliff below roughly 1% selectivity. Diagnose and fix."
  },
  {
    "id": "chunking-a-mixed-corpus",
    "n": 3,
    "title": "Chunking a mixed corpus",
    "layer": "retrieval",
    "asked": "Our knowledge base is 40% PDFs with tables, 30% Confluence pages, 20% source code, 10% support tickets. One chunking configuration is used for all of it and quality is poor everywhere. What do you change?"
  },
  {
    "id": "incremental-re-embedding",
    "n": 4,
    "title": "Freshness and incremental re-embedding",
    "layer": "retrieval",
    "asked": "Our corpus changes 2% per day. Full re-indexing takes 14 hours and costs $8,000. Retrieval quality decays visibly between runs and finance wants the bill halved. Redesign the ingestion pipeline."
  },
  {
    "id": "when-multi-agent-is-wrong",
    "n": 5,
    "title": "When multi-agent is the wrong answer",
    "layer": "orchestration",
    "asked": "A team proposes decomposing an existing single-agent workflow into seven specialized agents. Latency is currently 4 seconds and accuracy 88%. What do you ask before approving, and under what conditions do you reject it?"
  },
  {
    "id": "topology-and-context-isolation",
    "n": 6,
    "title": "Topology and context isolation",
    "layer": "orchestration",
    "asked": "Approved: the workload genuinely needs multiple agents. Design the topology for a research task where a supervisor must dispatch 5-20 parallel searches, and explain how you stop the supervisor's context from exploding."
  },
  {
    "id": "loop-termination-and-budget-gates",
    "n": 7,
    "title": "Loop termination and runtime budget gates",
    "layer": "orchestration",
    "asked": "An agent in production entered a tool-call loop and spent $4,000 in nine hours before anyone noticed. Design the controls so this cannot recur, without making the agent give up on legitimately long tasks."
  },
  {
    "id": "stateless-mcp-migration",
    "n": 8,
    "title": "Migrating an MCP fleet to the stateless specification",
    "layer": "orchestration",
    "asked": "We run 40 internal MCP servers on the 2025-11-25 revision. The 2026-07-28 revision removes protocol sessions and the initialize handshake entirely. Plan the migration for a fleet where several servers hold per-connection state."
  },
  {
    "id": "tool-namespace-explosion",
    "n": 9,
    "title": "Tool namespace explosion",
    "layer": "orchestration",
    "asked": "Our agent has access to 40 MCP servers exposing 400 tools. Tool selection accuracy has fallen below 60% and the tool definitions alone consume 60,000 tokens of every request. Fix both."
  },
  {
    "id": "the-mcp-caching-contract",
    "n": 10,
    "title": "The MCP caching contract",
    "layer": "caching",
    "asked": "Under revision 2026-07-28, tools/list results carry ttlMs and cacheScope, and servers should return tools in deterministic order. Design a client-side caching layer for a fleet serving a million agent calls a day, and explain what deterministic ordering has to do with cost."
  },
  {
    "id": "when-graphrag-earns-its-cost",
    "n": 11,
    "title": "When GraphRAG earns its indexing cost",
    "layer": "retrieval",
    "asked": "A team wants to replace our RAG with GraphRAG after a proof of concept showed better multi-hop answers. Indexing 2 million documents with LLM-based entity extraction is quoted at $180,000 and three weeks. Approve or reject?"
  },
  {
    "id": "the-query-routing-layer",
    "n": 12,
    "title": "The query routing layer",
    "layer": "retrieval",
    "asked": "Every query runs the full pipeline: rewrite, hybrid retrieve, rerank, frontier model. p50 is 3.2 seconds and $0.04 per query. Inspection suggests 60% of queries are trivial and repetitive. Design the router."
  },
  {
    "id": "the-long-context-trade-point",
    "n": 13,
    "title": "The long-context trade point",
    "layer": "caching",
    "asked": "A vendor argues we should drop retrieval entirely and use a 2 million token window. Our per-query corpus fits in about 800,000 tokens. Evaluate the proposal."
  },
  {
    "id": "multi-tenant-isolation",
    "n": 14,
    "title": "Multi-tenant isolation in a shared index",
    "layer": "retrieval",
    "asked": "500 enterprise tenants share one vector index. Legal now requires provable isolation. The largest tenant has 40 million documents, the smallest has 200. Design it."
  },
  {
    "id": "fusion-is-not-the-tuning-knob",
    "n": 15,
    "title": "Fusion is not the tuning knob",
    "layer": "retrieval",
    "asked": "We fused BM25 and dense retrieval with reciprocal rank fusion. Aggregate metrics improved but a set of queries got noticeably worse. The team wants to tune the RRF constant. What do you tell them?"
  },
  {
    "id": "proving-the-pipeline-is-better",
    "n": 16,
    "title": "Proving the new pipeline is better",
    "layer": "evaluation",
    "asked": "Cutover to the redesigned retrieval pipeline is in two weeks. We have no labelled relevance data. How do you show it is an improvement rather than a different set of failures?"
  },
  {
    "id": "handoff-contracts",
    "n": 17,
    "title": "Handoff contracts between agents",
    "layer": "orchestration",
    "asked": "Agent A extracts requirements, hands to B which produces a plan, hands to C which executes. Post-mortems keep tracing failures to information silently lost at a handoff. Fix it."
  },
  {
    "id": "compensation-mid-flight",
    "n": 18,
    "title": "Compensation when an agent fails mid-flight",
    "layer": "orchestration",
    "asked": "An agent with write access to CRM, billing and email failed after step 3 of 5. It had already issued a refund and sent a customer notification. What should the architecture have been?"
  },
  {
    "id": "approval-across-a-long-pause",
    "n": 19,
    "title": "Human approval across a three-day pause",
    "layer": "orchestration",
    "asked": "Any transaction above $10,000 requires human approval. Approvers respond in anywhere from four hours to three days. The agent currently holds an open connection and times out. Redesign."
  },
  {
    "id": "reproducing-a-failure",
    "n": 20,
    "title": "Reproducing a failure in a non-deterministic system",
    "layer": "evaluation",
    "asked": "A customer reported an agent failure six days ago. We have traces but cannot re-run it. Design for reproducibility."
  }
];

export const problemById = new Map(problems.map((p) => [p.id, p]));

export type RoadmapRow = {
  range: string;
  first: number;
  last: number;
  items: string;
  section: string;
};

export const roadmap: RoadmapRow[] = [
  {
    "range": "1-4",
    "first": 1,
    "last": 4,
    "items": "Catalog retrieval, filter selectivity, chunking, freshness",
    "section": "Context and retrieval"
  },
  {
    "range": "5-7",
    "first": 5,
    "last": 7,
    "items": "Multi-agent cost, topology, termination",
    "section": "Multi-agent"
  },
  {
    "range": "8-10",
    "first": 8,
    "last": 10,
    "items": "MCP stateless migration, tool namespace, cache contract",
    "section": "Protocol"
  },
  {
    "range": "11-16",
    "first": 11,
    "last": 16,
    "items": "Graph vs vector, query routing, long-context trade point, tenancy, fusion tuning, retrieval evaluation",
    "section": "Context and retrieval"
  },
  {
    "range": "17-20",
    "first": 17,
    "last": 20,
    "items": "Handoff contracts, compensation, human-in-the-loop, durable replay",
    "section": "Multi-agent"
  },
  {
    "range": "21-26",
    "first": 21,
    "last": 26,
    "items": "server/discover fleet negotiation, MRTR, tasks extension, supply chain, authorization, transport failure",
    "section": "Protocol"
  },
  {
    "range": "27-33",
    "first": 27,
    "last": 33,
    "items": "Cache-aware prompts, model cascades, budget enforcement, batch vs realtime, fine-tune break-even, self-host break-even, chargeback",
    "section": "Cost"
  },
  {
    "range": "34-39",
    "first": 34,
    "last": 39,
    "items": "p99 decomposition, streaming, backpressure, KV-aware routing, capacity planning, cold start",
    "section": "Latency and serving"
  },
  {
    "range": "40-43",
    "first": 40,
    "last": 43,
    "items": "Session vs long-term memory, temporal invalidation, erasure, state explosion",
    "section": "Memory"
  },
  {
    "range": "44-46",
    "first": 44,
    "last": 46,
    "items": "Bootstrapping evals, trajectory scoring, judge calibration",
    "section": "Evaluation"
  },
  {
    "range": "47-50",
    "first": 47,
    "last": 50,
    "items": "Injection through retrieved content, tenant PII and residency, regulatory classification, incident response",
    "section": "Governance"
  }
];

export const problemsPlanned = 50;
